import "./styles.css";
import { loadDetail, loadSearchData, SiteDataError } from "./data";
import { detailLink, displayValue, escapeHtml, safeExternalLink, triStateLabel } from "./display";
import { inValueOrder } from "./form-options";
import { emptyRequest, searchRows } from "./search";
import type { DetailRecord, FilterOptions, SearchRequest, SearchResult, SearchRow, SiteManifest } from "./types";
import { parseSearchParams, serializeRequest } from "./url-state";
import { registerSearchTools } from "./webmcp";

const PAGE_SIZE = 20;
const app = document.querySelector<HTMLDivElement>("#app")!;
let rows: SearchRow[] = [], options: FilterOptions, manifest: SiteManifest;
let applied = emptyRequest(), currentResult: SearchResult = searchRows([], applied);
let cleanupWebMcp: () => void = () => undefined;
const groupLabels = new Map<string, string>();

const header = () => `<header class="topbar"><a class="brand" href="/search" data-route><strong>2027年度 早期入試検索</strong></a><nav><a href="/search" data-route>検索</a><a href="/about/data" data-route>データについて</a></nav></header>`;
const footer = () => `<footer>候補の絞り込み用です。出願前に最新の公式資料を必ず確認してください。</footer>`;
const selected = (field: string, value: string) => ((applied[field as keyof SearchRequest] as string[]) ?? []).includes(value);
function checks(field: string, items: Array<{value:string|null;display_label:string}>, labels:Record<string,string>={}):string {
  return `<div class="check-grid">${items.filter(x=>x.value!==null).map(x=>`<label class="check"><input type="checkbox" name="${field}" value="${escapeHtml(x.value!)}" ${selected(field,x.value!)?"checked":""}> <span>${escapeHtml(labels[x.value!]??x.display_label)}</span></label>`).join("")}</div>`;
}
function radios(field:string, choices:Array<[string,string]>):string { const current=((applied[field as keyof SearchRequest] as string[])??[])[0]??""; return `<div class="radio-row">${choices.map(([v,l])=>`<label><input type="radio" name="${field}" value="${v}" ${current===v?"checked":""}> ${l}</label>`).join("")}</div>`; }
function searchForm():string {
  const groups=options.academic_field_groups.map(x=>({value:x.value,display_label:x.display_label}));
  const institutionTypes=inValueOrder(options.institution_types,["国立","公立","私立"]);
  const exclusive=inValueOrder(options.exclusive_enrollment_statuses.filter(x=>["専願","併願可","条件付き","不明"].includes(x.value??"")),["専願","併願可","条件付き","不明"]);
  const methods:Array<[string,string]>=[["selection_interview","面接"],["selection_oral_exam","口頭試問"],["selection_presentation","プレゼン"],["selection_essay","小論文"],["selection_written_exam","筆記試験"]];
  const regions=["北海道・東北","関東","中部","近畿","中国・四国","九州・沖縄"];
  const prefectures=regions.map(region=>`<section class="prefecture-region"><h3>${region}</h3>${checks("prefecture_membership",options.prefecture_memberships.filter(x=>x.region===region))}</section>`).join("");
  return `<form id="search-form" class="search-form"><header class="form-intro"><h1>条件から入試を探す</h1><p>異なる項目はすべて満たすもの、同じ項目の複数選択はいずれかに一致するものを検索します。</p></header>
  <fieldset><legend>1. 学問分野</legend><p class="help">複数選択可</p>${checks("academic_field_group",groups)}</fieldset>
  <fieldset><legend>2. 大学種別</legend>${checks("institution_type",institutionTypes)}</fieldset>
  <fieldset><legend>3. 専願・併願</legend>${checks("exclusive_enrollment_status",exclusive,{不明:"不明・記載確認できず"})}</fieldset>
  <fieldset><legend>4. 共通テスト</legend>${radios("common_test_required",[["","指定なし"],["Yes","あり"],["No","なし"]])}</fieldset>
  <fieldset><legend>5. 研究業績</legend>${radios("research_requirement_required",[["","指定なし"],["Yes","必要"],["No","必要なし"]])}</fieldset>
  <fieldset><legend>6. 英語資格</legend>${radios("english_requirement_status",[["","指定なし"],["required","必要"],["not_required","必要なし"]])}</fieldset>
  <fieldset><legend>7. 試験内容</legend><p class="help">複数選ぶと、すべて実施する入試に絞ります。</p><div class="check-grid">${methods.map(([f,l])=>`<label class="check"><input type="checkbox" name="${f}" value="Yes" ${selected(f,"Yes")?"checked":""}> <span>${l}</span></label>`).join("")}</div></fieldset>
  <fieldset><legend>8. 評定</legend><label class="input-label" for="gpa">評定値（0.0〜5.0）</label><input id="gpa" type="number" min="0" max="5" step="0.1" value="${applied.gpa_tenths===null?"":(applied.gpa_tenths/10).toFixed(1)}"><p class="help">単純な全体評定の数値条件のみを安全に照合します。</p></fieldset>
  <fieldset class="prefecture-fieldset"><details id="prefecture-details"><summary>9. 都道府県で絞り込む <span id="prefecture-count" class="selected-count"></span></summary><div class="prefecture-regions">${prefectures}</div><button id="clear-prefectures" type="button">選択をクリア</button></details></fieldset>
  <div id="form-error" class="notice error" hidden></div><div class="form-actions"><button class="primary" type="submit">この条件で検索</button><button id="clear-form" type="button">条件をクリア</button></div></form>`;
}
function readForm():SearchRequest|null {
  const form=document.querySelector<HTMLFormElement>("#search-form")!, request=emptyRequest();
  for(const field of ["academic_field_group","institution_type","exclusive_enrollment_status","selection_interview","selection_oral_exam","selection_presentation","selection_essay","selection_written_exam","prefecture_membership"] as const) request[field]=[...form.querySelectorAll<HTMLInputElement>(`input[name="${field}"]:checked`)].map(x=>x.value);
  for(const field of ["common_test_required","research_requirement_required","english_requirement_status"] as const){const value=form.querySelector<HTMLInputElement>(`input[name="${field}"]:checked`)?.value??"";request[field]=value?[value]:[];}
  const raw=form.querySelector<HTMLInputElement>("#gpa")!.value.trim();
  if(raw){if(!/^(?:[0-4](?:\.\d)?|5(?:\.0)?)$/.test(raw)){const e=document.querySelector<HTMLElement>("#form-error")!;e.hidden=false;e.textContent="評定は0.0〜5.0、小数1桁までで入力してください。";return null;}request.gpa_tenths=Math.round(Number(raw)*10);request.gpa_mode="safe";}
  return request;
}
function updatePrefectureCount():void {const n=document.querySelectorAll('input[name="prefecture_membership"]:checked').length;const o=document.querySelector("#prefecture-count");if(o)o.textContent=n?`（${n}件選択）`:"";}
function bindForm():void {document.querySelector("#search-form")!.addEventListener("submit",e=>{e.preventDefault();const next=readForm();if(!next)return;const q=serializeRequest(next).toString();history.pushState({},"",`/results${q?`?${q}`:""}`);void route();});document.querySelector("#clear-form")!.addEventListener("click",()=>{applied=emptyRequest();searchPage([]);});document.querySelector("#clear-prefectures")!.addEventListener("click",()=>{document.querySelectorAll<HTMLInputElement>('input[name="prefecture_membership"]:checked').forEach(x=>x.checked=false);updatePrefectureCount();});document.querySelectorAll('input[name="prefecture_membership"]').forEach(x=>x.addEventListener("change",updatePrefectureCount));updatePrefectureCount();}
function searchPage(warnings:string[]):void {app.innerHTML=`${header()}<main class="page search-page">${warnings.map(w=>`<div class="notice">${escapeHtml(w)}</div>`).join("")}${searchForm()}</main>${footer()}`;bindForm();}
function resultCard(row:SearchRow):string {const groups=row.academic_field_groups.map(x=>groupLabels.get(x)??x).join("・")||"—";const methods=[["面接",row.selection_interview],["口頭試問",row.selection_oral_exam],["プレゼン",row.selection_presentation],["小論文",row.selection_essay],["筆記",row.selection_written_exam]].filter(([,v])=>v==="Yes").map(([l])=>l).join("・")||"—";return `<article class="result-card"><p class="meta">${displayValue(row.prefecture)} ／ ${escapeHtml(row.institution_type)}${row.fallback_previous_year?" ／ 前年度情報":""}</p><h2><a href="${detailLink(row.source_dataset,row.source_version,row.record_id)}" data-route>${escapeHtml(row.university)}</a></h2><p>${displayValue(row.faculty_school)} ／ ${displayValue(row.department)}</p><p><strong>${displayValue(row.selection_category)}</strong>　${displayValue(row.selection_name)}</p><dl class="result-facts"><div><dt>募集人数</dt><dd>${displayValue(row.capacity)}</dd></div><div><dt>学問分野</dt><dd>${escapeHtml(groups)}</dd></div><div><dt>専願・併願</dt><dd>${displayValue(row.exclusive_enrollment_status)}</dd></div><div><dt>評定条件（原文）</dt><dd>${displayValue(row.gpa_requirement)}</dd></div><div><dt>共通テスト</dt><dd>${escapeHtml(triStateLabel(row.common_test_required,"あり","なし"))}</dd></div><div><dt>研究実績要件</dt><dd>${escapeHtml(triStateLabel(row.research_requirement_required,"必要","必要なし"))}</dd></div><div><dt>選考内容</dt><dd>${methods}</dd></div><div><dt>出願期間（原文）</dt><dd>${displayValue(row.application_start)} 〜 ${displayValue(row.application_end)}</dd></div></dl><a href="${detailLink(row.source_dataset,row.source_version,row.record_id)}" data-route>詳細と公式資料を確認 →</a></article>`;}
function summary():string {const p:string[]=[];if(applied.academic_field_group.length)p.push(`学問分野：${applied.academic_field_group.map(x=>groupLabels.get(x)??x).join("、")}`);if(applied.institution_type.length)p.push(`大学種別：${applied.institution_type.join("、")}`);if(applied.exclusive_enrollment_status.length)p.push(`専願・併願：${applied.exclusive_enrollment_status.join("、")}`);if(applied.common_test_required.length)p.push(`共通テスト：${applied.common_test_required[0]==="Yes"?"あり":"なし"}`);if(applied.research_requirement_required.length)p.push(`研究業績：${applied.research_requirement_required[0]==="Yes"?"必要":"必要なし"}`);if(applied.english_requirement_status.length)p.push(`英語資格：${applied.english_requirement_status[0]==="required"?"必要":"必要なし"}`);if(applied.gpa_tenths!==null)p.push(`評定：${(applied.gpa_tenths/10).toFixed(1)}（安全照合）`);if(applied.prefecture_membership.length)p.push(`都道府県：${applied.prefecture_membership.join("、")}`);return (p.length?p:["条件指定なし"]).map(x=>`<li>${escapeHtml(x)}</li>`).join("");}
function resultsPage(warnings:string[]):void {currentResult=searchRows(rows,applied);const pages=Math.max(1,Math.ceil(currentResult.rows.length/PAGE_SIZE));if(applied.page>pages)applied.page=pages;const shown=currentResult.rows.slice((applied.page-1)*PAGE_SIZE,applied.page*PAGE_SIZE);const q=serializeRequest({...applied,page:1}).toString();app.innerHTML=`${header()}<main class="page results-page"><section class="results-summary"><h1>${currentResult.summary.total_matched_rows.toLocaleString("ja-JP")}件</h1><p>${currentResult.summary.university_count.toLocaleString("ja-JP")}大学</p><ul>${summary()}</ul><a href="/search${q?`?${q}`:""}" data-route>検索条件を変更</a></section>${warnings.map(w=>`<div class="notice">${escapeHtml(w)}</div>`).join("")}<div class="results">${shown.length?shown.map(resultCard).join(""):'<section class="empty"><h2>該当する入試がありません</h2><p>条件を減らして検索してください。</p></section>'}</div>${pages>1?`<nav class="pagination"><button data-page="${applied.page-1}" ${applied.page<=1?"disabled":""}>前へ</button><span>${applied.page} / ${pages}</span><button data-page="${applied.page+1}" ${applied.page>=pages?"disabled":""}>次へ</button></nav>`:""}</main>${footer()}`;}

const sections:Array<[string,string[]]>=[["基本情報",["admission_year","institution_type","university","prefecture","faculty_school","department","academic_field","selection_category","selection_name","slot_type","capacity"]],["選考方法",["selection_process","selection_method_detail","selection_document_review","selection_interview","interview_detail","selection_oral_exam","oral_exam_subjects","oral_exam_detail","selection_presentation","presentation_detail","selection_essay","essay_detail","selection_written_exam","written_exam_detail","selection_common_test","selection_group_discussion","selection_practical","selection_aptitude_test","documents_summary"]],["出願条件",["eligibility_graduation","gpa_requirement","english_requirement","subject_prerequisites","school_recommendation_required","school_nomination_limit","school_nomination_limit_total","school_nomination_limit_rule","exclusive_enrollment_status","exclusive_enrollment","common_test_required","common_test_usage","academic_record_required","academic_record_type","academic_record_detail"]],["日程",["application_start","application_end","web_registration_period","first_stage_result_date","second_stage_start","second_stage_end","final_result_date"]],["研究",["research_requirement_required","research_requirement_summary","research_activity_level_status","research_activity_level_raw","research_activity_detail"]]];
const labels:Record<string,string>={admission_year:"入試年度",institution_type:"大学種別",university:"大学",prefecture:"都道府県",faculty_school:"学部等",department:"学科等",academic_field:"学問分野（原文）",selection_category:"選抜区分",selection_name:"選抜名称",slot_type:"枠・型",capacity:"募集人数",selection_process:"選考過程",selection_method_detail:"選考方法詳細",selection_document_review:"書類審査",selection_interview:"面接",interview_detail:"面接詳細",selection_oral_exam:"口頭試問",oral_exam_subjects:"口頭試問科目",oral_exam_detail:"口頭試問詳細",selection_presentation:"プレゼン",presentation_detail:"プレゼン詳細",selection_essay:"小論文",essay_detail:"小論文詳細",selection_written_exam:"筆記",written_exam_detail:"筆記詳細",selection_common_test:"共通テスト利用",selection_group_discussion:"グループ討論",selection_practical:"実技",selection_aptitude_test:"適性検査",documents_summary:"提出書類",eligibility_graduation:"卒業等の要件",gpa_requirement:"評定条件（原文）",english_requirement:"英語資格・検定条件（原文）",subject_prerequisites:"科目等の前提",school_recommendation_required:"学校推薦",school_nomination_limit:"学校別推薦人数",school_nomination_limit_total:"推薦人数合計",school_nomination_limit_rule:"推薦人数規則",exclusive_enrollment_status:"専願・併願",exclusive_enrollment:"専願等の詳細",common_test_required:"共通テスト",common_test_usage:"共通テストの扱い",academic_record_required:"調査書等",academic_record_type:"調査書等の種類",academic_record_detail:"調査書等の詳細",application_start:"出願開始（原文）",application_end:"出願終了（原文）",web_registration_period:"ウェブ登録期間（原文）",first_stage_result_date:"第1段階結果（原文）",second_stage_start:"第2段階開始（原文）",second_stage_end:"第2段階終了（原文）",final_result_date:"最終結果（原文）",research_requirement_required:"研究実績要件",research_requirement_summary:"研究実績要件概要",research_activity_level_status:"研究活動水準",research_activity_level_raw:"研究活動水準（原文）",research_activity_detail:"研究活動詳細"};
Object.assign(labels,{stem_flag:"理系区分",exclusive_enrollment_evidence:"専願・併願の根拠",exclusive_enrollment_evidence_page:"根拠ページ",source_status:"情報源の状態",detail_completeness_status:"詳細情報の充足状況",detail_completeness_raw:"詳細情報の充足状況（原文）",verification_grade:"確認水準",verified_on:"確認日",notes:"注記",information_year:"情報年度",publication_status:"公開状況",current_year_release_expected:"当年度公開見込み",fallback_previous_year:"前年度情報",fallback_note:"前年度情報の注記"});
const formatted=(value:unknown)=>value==="Yes"?"あり":value==="No"?"なし":value==="Unknown"?"不明":displayValue(value as never);
const grid=(record:Record<string,unknown>,fields:string[])=>`<dl class="detail-grid">${fields.map(f=>`<div><dt>${escapeHtml(labels[f]??"記録項目")}</dt><dd>${formatted(record[f])}</dd></div>`).join("")}</dl>`;
function research(detail:DetailRecord):string{return detail.research_requirements.length?detail.research_requirements.map((r,i)=>`<article class="child-row"><h3>詳細 ${i+1}</h3>${grid(r,Object.keys(r).filter(k=>k!=="research_rowid"))}</article>`).join(""):"<p>構造化された研究要件の詳細行はありません。</p>";}
async function detailPage(parts:string[]):Promise<void>{const [dataset,version,id]=parts.map(decodeURIComponent),row=rows.find(r=>r.source_dataset===dataset&&r.source_version===version&&r.record_id===id);if(!row){dataError("指定された入試が見つかりません。");return;}app.innerHTML=`${header()}<main class="page">読み込んでいます…</main>`;try{const {detail}=await loadDetail(manifest,row),a=detail.admission,assigned=new Set(sections.flatMap(([,f])=>f)),hidden=new Set(["admission_rowid","source_url","guideline_url","schedule_url","exclusive_enrollment_evidence_url","previous_year_source_url"]),remaining=Object.keys(a).filter(f=>!assigned.has(f)&&!hidden.has(f));app.innerHTML=`${header()}<main class="page detail-page"><p><a href="${history.state?.from??"/results"}" data-route>← 検索結果へ戻る</a></p>${a.fallback_previous_year===true?'<div class="fallback-warning"><strong>前年度情報を参照しています。</strong> 2027年度の公式資料を確認してください。</div>':""}<header class="detail-title"><p>${displayValue(a.prefecture as never)} ／ ${displayValue(a.institution_type as never)}</p><h1>${displayValue(a.university as never)}</h1><p>${displayValue(a.faculty_school as never)} ／ ${displayValue(a.department as never)}</p><p><strong>${displayValue(a.selection_category as never)}</strong>　${displayValue(a.selection_name as never)}</p></header><p class="eligibility-note">このページは出願資格や合格可能性を判定しません。</p>${sections.map(([t,f])=>`<section class="detail-section"><h2>${t}</h2>${grid(a,f)}${t==="研究"?research(detail):""}</section>`).join("")}<section class="detail-section"><h2>その他の記録項目</h2>${grid(a,remaining)}</section><section class="detail-section"><h2>出典</h2><div class="source-links">${safeExternalLink(a.guideline_url,"募集要項")}${safeExternalLink(a.source_url,"公式情報")}${safeExternalLink(a.schedule_url,"日程")}${safeExternalLink(a.exclusive_enrollment_evidence_url,"専願根拠")}${safeExternalLink(a.previous_year_source_url,"前年度資料")}</div><details class="developer-details"><summary>データ識別情報</summary><p>${escapeHtml(dataset)} ／ ${escapeHtml(version)} ／ ${escapeHtml(id)}</p></details></section></main>${footer()}`;}catch(error){dataError(error instanceof SiteDataError?error.message:"詳細データを読み込めませんでした。");}}
function aboutPage():void{app.innerHTML=`${header()}<main class="page narrow about"><h1>データについて</h1><section><h2>検索結果の意味</h2><p>条件に一致する候補を絞り込むためのもので、出願資格・条件充足・合格可能性を判定しません。</p><p>評定は単純な全体評定の数値条件だけ、英語資格は監査済みの完全一致表現だけを安全に検索します。</p></section><section><h2>原文と不明値</h2><p>「なし」「不明」「未記録」は区別して保持しています。学問分野の19分類は検索用の派生分類です。</p></section><details class="developer-details"><summary>データ版情報</summary><p>構築ID：${escapeHtml(manifest.build_id)}</p><p>件数：${manifest.counts.search_rows.toLocaleString("ja-JP")}</p></details></main>${footer()}`;}
function dataError(message:string):void{app.innerHTML=`${header()}<main class="page"><section class="error"><h1>データを表示できません</h1><p>${escapeHtml(message)}</p></section></main>${footer()}`;}
async function route(replace=false):Promise<void>{const path=location.pathname.replace(/\/+$/,"")||"/";if(path==="/about/data"){aboutPage();return;}const match=path.match(/^\/admissions\/([^/]+)\/([^/]+)\/([^/]+)$/);if(match){await detailPage(match.slice(1));return;}if(path==="/"){history.replaceState({},"","/search");searchPage([]);return;}if(path!=="/search"&&path!=="/results"){dataError("ページが見つかりません。");return;}const parsed=parseSearchParams(new URLSearchParams(location.search),options);applied=parsed.request;if(replace&&path==="/results"){const q=serializeRequest(applied).toString();history.replaceState({},"",`/results${q?`?${q}`:""}`);}path==="/search"?searchPage(parsed.warnings):resultsPage(parsed.warnings);}
document.addEventListener("click",e=>{const target=e.target as HTMLElement,link=target.closest<HTMLAnchorElement>("a[data-route]");if(link&&link.origin===location.origin){e.preventDefault();history.pushState({from:location.pathname+location.search},"",link.href);void route();return;}const page=target.closest<HTMLButtonElement>("button[data-page]");if(page){applied.page=Number(page.dataset.page);const q=serializeRequest(applied).toString();history.pushState({},"",`/results?${q}`);resultsPage([]);scrollTo({top:0});}});window.addEventListener("popstate",()=>void route());
try{const loaded=await loadSearchData();rows=loaded.rows;options=loaded.options;manifest=loaded.manifest;for(const g of options.academic_field_groups)groupLabels.set(g.value,g.display_label);await route(true);cleanupWebMcp();cleanupWebMcp=registerSearchTools(async partial=>{applied={...emptyRequest(),...partial,page:1} as SearchRequest;if(applied.gpa_tenths!==null)applied.gpa_mode="safe";const q=serializeRequest(applied).toString();history.pushState({},"",`/results${q?`?${q}`:""}`);resultsPage([]);return{total:currentResult.summary.total_matched_rows,universities:currentResult.summary.university_count};},()=>({total:currentResult.summary.total_matched_rows,universities:currentResult.summary.university_count,url:location.href}));}catch(error){dataError(error instanceof SiteDataError?error.message:"データの読み込み中に問題が発生しました。");}
